### ISSUE TITLE
wl bug in ipv4 feed?

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/cif-sdk-py#87]
```
(venv)user@cifv2-client:~/cif-sdk-py$ ./venv/bin/cif -C ../file.yml --otype ipv4 --feed -c 85 -f json -d > /dev/null
2016-04-12 09:05:24,484 - DEBUG - cifsdk.client[89] - uri: https://<redacted>/observables
2016-04-12 09:05:24,484 - DEBUG - cifsdk.client[90] - params: {"confidence":"85","reporttime":"2016-04-09T18:05:24Z","nolog":null,"otype":"ipv4","limit":null,"reporttimeend":"2016-04-12T18:05:24Z","gzip":1}
2016-04-12 09:05:24,484 - INFO - cifsdk.client[92] - searching...
2016-04-12 09:05:24,489 - INFO - requests.packages.urllib3.connectionpool[758] - Starting new HTTPS connection (1): <redacted>
2016-04-12 09:06:25,397 - DEBUG - requests.packages.urllib3.connectionpool[387] - "GET /observables?confidence=85&reporttime=2016-04-09T18%3A05%3A24Z&otype=ipv4&reporttimeend=2016-04-12T18%3A05%3A24Z&gzip=1 HTTP/1.1" 200 11965018
2016-04-12 09:06:27,868 - DEBUG - cifsdk.client[96] - status code: 200
2016-04-12 09:06:27,869 - INFO - cifsdk.client[103] - processing 11 megs
2016-04-12 09:06:27,869 - INFO - cifsdk.client[107] - trying to decompress...
2016-04-12 09:06:28,043 - INFO - cifsdk.client[113] - decoding...
2016-04-12 09:06:28,959 - INFO - cifsdk.client[116] - sorting...
2016-04-12 09:06:29,012 - DEBUG - cifsdk.client[122] - returning..
2016-04-12 09:06:29,012 - DEBUG - cifsdk.client[89] - uri: https://<redacted>/observables
2016-04-12 09:06:29,013 - DEBUG - cifsdk.client[90] - params: {"confidence":25,"reporttime":"2016-04-09T18:06:29Z","tags":"whitelist","nolog":true,"otype":"ipv4","limit":25000,"reporttimeend":"2016-04-12T18:05:24Z","gzip":1}
2016-04-12 09:06:29,013 - INFO - cifsdk.client[92] - searching...
2016-04-12 09:06:34,093 - DEBUG - requests.packages.urllib3.connectionpool[387] - "GET /observables?confidence=25&reporttime=2016-04-09T18%3A06%3A29Z&tags=whitelist&nolog=True&otype=ipv4&limit=25000&reporttimeend=2016-04-12T18%3A05%3A24Z&gzip=1 HTTP/1.1" 200 4078346
2016-04-12 09:06:35,377 - DEBUG - cifsdk.client[96] - status code: 200
2016-04-12 09:06:35,377 - INFO - cifsdk.client[103] - processing 3 megs
2016-04-12 09:06:35,377 - INFO - cifsdk.client[107] - trying to decompress...
2016-04-12 09:06:35,438 - INFO - cifsdk.client[113] - decoding...
2016-04-12 09:06:36,055 - INFO - cifsdk.client[116] - sorting...
2016-04-12 09:06:36,069 - DEBUG - cifsdk.client[122] - returning..
Traceback (most recent call last):
  File "./venv/bin/cif", line 9, in <module>
    load_entry_point('cif-sdk-py==2.0.0a3', 'console_scripts', 'cif')()
  File "/home/user/cif-sdk-py/venv/local/lib/python2.7/site-packages/cifsdk/client.py", line 407, in main
    ret = f().process(ret, wl)
  File "/home/user/cif-sdk-py/venv/local/lib/python2.7/site-packages/cifsdk/feed/ipv4.py", line 52, in process
    wl[y] = True
SystemError: error return without exception set
```

**Comment by giovino** [comment]
installed on a ubuntu 14.03.03 box:

```
$ sudo apt-get install -y python-dev python-pip git
$ mkdir cif-sdk-py && cd cif-sdk-py/
$ virtualenv venv
$ source venv/bin/activate
$ pip install -U pip
$ pip install git+https://github.com/csirtgadgets/cif-sdk-py
```

pip freeze output
```
$ pip freeze
arrow==0.6.0
cif-sdk-py==2.0.0a3
prettytable==0.7.2
py==1.4.31
pytest==2.9.1
python-dateutil==2.5.2
pytricia==0.9.0
PyYAML==3.11
requests==2.9.1
six==1.10.0
tailer==0.3
ujson==1.34
```

**Comment by giovino** [comment]
the pytricia module doesn't like preceding zero in an ip address

```
>>> import pytricia
>>> pyt = pytricia.PyTricia()
>>> pyt["184.168.047.225/32"] = True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: error return without exception set
```
