### ISSUE TITLE
IOError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/cif-sdk-py#94]
```
 $ cif --feed --otype fqdn --provider spamhaus.org --format csv | head -n 3
"
tlp","group","lasttime","reporttime","observable","otype","cc","asn","asn_desc","confidence","description","tags","rdata","rtype","provider","altid","altid_tlp"
"privileged","xxx","2016-03-31T00:16:45Z","2016-03-31T00:16:45Z","ns1.whitesnakecatch.top","fqdn","","","","95","spammed domain","suspicious","ns1.whitesnakecatch.top","","spamhaus.org","http://www.spamhaus.org/query/dbl?domain=ns1.whitesnakecatch.top","limited"
"privileged","xxx","2016-03-31T00:16:45Z","2016-03-31T00:16:45Z","ns2.wareasy.link","fqdn","","","","95","spammed domain","suspicious","ns2.wareasy.link","","spamhaus.org","http://www.spamhaus.org/query/dbl?domain=ns2.wareasy.link","limited"
Traceback (most recent call last):
  File "/home/xx/py-submit/venv/bin/cif", line 9, in <module>
    load_entry_point('cif-sdk-py===2.0.0a3-9-g7eb2c73', 'console_scripts', 'cif')()
  File "/home/xx/py-submit/venv/local/lib/python2.7/site-packages/cifsdk/client.py", line 428, in main
    print(ret)
IOError: [Errno 32] Broken pipe
```

print the output [outside of the loop](https://github.com/csirtgadgets/cif-sdk-py/blob/master/cifsdk/client.py#L428)?

**Comment by wesyoung** [comment]
i noticed that too; it has something to do with the csv output plugin specifically. not sure if it's a bug or feature. only happens "when you pipe" into something else...

**Comment by giovino** [comment]
Stackoverflow answer
http://stackoverflow.com/questions/14207708/ioerror-errno-32-broken-pipe-python/35761190#35761190

Pip's answer
https://github.com/pypa/pip/pull/3304/commits/b55d84986fb0f9607f3039d1a525432f5ec487e4

I confirmed that this fixes the problem, question is.. do we want to do it. 

```
from signal import signal, SIGPIPE, SIG_DFL
...
...

        try:
            if len(ret) >= 1:
                ret = f(ret, cols=options['fields'].split(','))
                if args.filename:
                    with open(args.filename, 'w') as F:
                        F.write(str(ret))
                else:
                    signal(SIGPIPE, SIG_DFL)
                    print(ret)
```

**Comment by wesyoung** [comment]
yea, i'm OK with that if you wanna PR it...
